services:
  selenium-service:
    build: .
    image: selenium-service:latest
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    shm_size: "2gb"        # important for Chrome stability
    environment:
      - TZ=America/Denver
      - API_TOKEN=9b1327ac67aac1f8a12579293a6f1d3c21c098874f40abce8b109b4eaa94b1a5
